### ISSUE TITLE
Command line utility not working on Windows

### ISSUE THREAD

**Issue by johnthagen** [initios/flake8-junit-report#17]
On Windows 10 using Python 3.5.1:

```bat
>pip -V
pip 8.0.2
>pip install flake8-junit-report
>pip list
...
flake8-junit-report (2.0.1)
...
>flake8_junit
'flake8_junit' is not recognized as an internal or external command,
operable program or batch file.
```

I think what you want is something like a `console_scripts` [`entry_point`](https://pythonhosted.org/setuptools/setuptools.html#new-and-changed-setup-keywords):
```python
setuptools.setup(
    ...
    entry_points={
            'console_scripts': [
                'flake8_junit = (INSERT MAIN MODULE):main',
            ],
```

This will work on Linux and Windows.

**Comment by carlosgoce** [comment]
Hello, 

I tried this and it worked on Windows 7.

```shell
C:\Users\Carlos>python --version
Python 3.5.1

C:\Users\Carlos>pip install flake8-junit-report
Collecting flake8-junit-report
  Downloading flake8-junit-report-2.0.1.tar.gz
Installing collected packages: flake8-junit-report
  Running setup.py install for flake8-junit-report
Successfully installed flake8-junit-report-2.0.1


C:\Users\Carlos>python --version
Python 3.5.1

C:\Users\Carlos>pip list
flake8-junit-report (2.0.1)
pip (8.0.3)
setuptools (18.2)
```

However I will try it on Windows 10.
What is your pip version?

**Comment by johnthagen** [comment]
@carlosgoce The `pip` version is 8.0.2.

The problem I am specifically referring to, however, is that the final `flake8_junit` command fails on Windows because there is no console entry point.  `pip` installs the package into site-packages fine.

**Comment by carlosgoce** [comment]
I was in a hurry and I missed that line. I will fix it soon. Thank you.

**Comment by johnthagen** [comment]
@carlosgoce Just checking in to make sure this issue hadn't been lost, is it still possible to fix this issue and upload a new version to PyPI?  Thanks.

**Comment by carlosgoce** [comment]
Sorry I forgot it. Will check it out this week ASAP

**Comment by carlosgoce** [comment]
Finally! It should be fixed

**Comment by johnthagen** [comment]
Works, thanks!
